apiVersion: ingress.oraclecloud.com/v1beta1
kind: IngressClassParameters
metadata:
  name: {{ .Values.ingressClassParameters.name }}
  namespace: {{ .Values.ingressClassParameters.namespace }}
  labels:
    app: {{ include "front-app.name" . }}
    chart: {{ include "front-app.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  compartmentId: "{{ .Values.ingressClassParameters.compartmentId }}"
  subnetId: "{{ .Values.ingressClassParameters.subnetId }}"
  loadBalancerName: "{{ .Values.ingressClassParameters.loadBalancerName }}"
  isPrivate: {{ .Values.ingressClassParameters.isPrivate }}
  maxBandwidthMbps: {{ .Values.ingressClassParameters.maxBandwidthMbps }}
  minBandwidthMbps: {{ .Values.ingressClassParameters.minBandwidthMbps }}