apiVersion: ingress.oraclecloud.com/v1beta1
kind: IngressClassParameters
metadata:
  name: {{ .Values.ingressClassParameters.name }}
  namespace: {{ .Values.ingressClassParameters.namespace }}
  labels:
    app: {{ include "front-app.name" . }}
    chart: {{ include "front-app.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  compartmentId: "{{ .Values.ingressClassParameters.compartmentId }}"
  subnetId: "{{ .Values.ingressClassParameters.subnetId }}"
  {{- if and .Values.ingressClassParameters.dynamicLoadBalancerName (eq .Values.ingressClassParameters.dynamicLoadBalancerName.enabled true) }}
  loadBalancerName: "{{ if .Values.ingressClassParameters.dynamicLoadBalancerName.prefix }}{{ .Values.ingressClassParameters.dynamicLoadBalancerName.prefix }}{{ .Values.ingressClassParameters.dynamicLoadBalancerName.separator }}{{ end }}{{ if .Values.ingressClassParameters.dynamicLoadBalancerName.includeNamespace }}{{ .Release.Namespace }}{{ .Values.ingressClassParameters.dynamicLoadBalancerName.separator }}{{ end }}{{ if .Values.ingressClassParameters.dynamicLoadBalancerName.includeReleaseName }}{{ .Release.Name }}{{ .Values.ingressClassParameters.dynamicLoadBalancerName.separator }}{{ end }}lb{{ if .Values.ingressClassParameters.dynamicLoadBalancerName.suffix }}{{ .Values.ingressClassParameters.dynamicLoadBalancerName.separator }}{{ .Values.ingressClassParameters.dynamicLoadBalancerName.suffix }}{{ end }}"
  {{- else }}
  loadBalancerName: "{{ .Values.ingressClassParameters.loadBalancerName }}"
  {{- end }}
  isPrivate: {{ .Values.ingressClassParameters.isPrivate }}
  maxBandwidthMbps: {{ .Values.ingressClassParameters.maxBandwidthMbps }}
  minBandwidthMbps: {{ .Values.ingressClassParameters.minBandwidthMbps }}