apiVersion: v1
kind: Service
metadata:
  name: {{ include "front-app.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "front-app.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    chart: {{ include "front-app.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app.kubernetes.io/name: {{ include "front-app.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: http
      port: {{ .Values.service.ports.http.port }}
      targetPort: {{ .Values.service.ports.http.targetPort }}
      {{- if .Values.service.ports.http.nodePort }}
      nodePort: {{ .Values.service.ports.http.nodePort }}
      {{- end }}
    - name: https
      port: {{ .Values.service.ports.https.port }}
      targetPort: {{ .Values.service.ports.https.targetPort }}
      {{- if .Values.service.ports.https.nodePort }}
      nodePort: {{ .Values.service.ports.https.nodePort }}
      {{- end }}
